### ISSUE TITLE
Specify project LICENSE

### ISSUE THREAD

**Issue by stvstnfrd** [annotationsatharvard/catcha#38]
Under which license is this code released?

I'm interested in contributing to this project, but I want to confirm
its license before doing so. I'm not seeing the license mentioned
anywhere explicitly.

`CREDITS.TXT` lists dependencies on L/GPL assets [0], but it does not
specify if this is GPLv2 or GPLv3. Unfortnately, the provided URLs all
404, as the host no longer appears to exist [1].

Feel free to check out the AGPLv3 (Affero General Public License) [2].
This is the same license used by the edX project [3].

Would you mind clarifying?

[0] https://github.com/annotationsatharvard/catcha/blob/master/Catch/CREDITS.TXT
[1] http://www.iconlet.com
[2] http://www.gnu.org/licenses/agpl.html
[3] https://github.com/edx/edx-platform/blob/master/LICENSE

**Comment by stvstnfrd** [comment]
I'm going to close this as my need has lapsed; thank you and take care @jmiranda !

**Comment by jmiranda** [comment]
Hey @stvstnfrd. Sorry for not following up on this ticket. Best of luck. 

Fwiw, I was under the impression that people had moved on from this project long ago so I stopped giving it much attention. But I'm happy to keep the project going (merge pull requests, small bug fixes, upgrades, etc) if there's still interest or urgent needs that come up. 

For anyone interested, HarvardX ported the annotation API code to Python back in 2017 (https://github.com/nmaekawa/catchpy) so that their internal devs could maintain and extend the platform. Contact @nmaekawa for more information.
